--
-- Script was generated by Devart dbForge Studio for MySQL, Version 8.0.40.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/30/2020 12:08:39 AM
-- Server version: 8.0.17
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE digital_signage;

--
-- Drop table `frame`
--
DROP TABLE IF EXISTS frame;

--
-- Drop table `panel`
--
DROP TABLE IF EXISTS panel;

--
-- Drop table `screen`
--
DROP TABLE IF EXISTS screen;

--
-- Drop table `user`
--
DROP TABLE IF EXISTS user;

--
-- Drop table `user_type`
--
DROP TABLE IF EXISTS user_type;

--
-- Set default database
--
USE digital_signage;

--
-- Create table `user_type`
--
CREATE TABLE user_type (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `user`
--
CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  username varchar(255) DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  user_type_id int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `screen`
--
CREATE TABLE screen (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  password varchar(255) DEFAULT NULL,
  width int(11) DEFAULT NULL,
  height int(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `panel`
--
CREATE TABLE panel (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Một vùng không gian hiển thị trong Canvas chứa 1 or nhiều Frame';

--
-- Create table `frame`
--
CREATE TABLE frame (
  id int(11) NOT NULL AUTO_INCREMENT,
  name varchar(50) DEFAULT NULL,
  type varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table user_type
--
INSERT INTO user_type VALUES
(1, 'management'),
(2, 'client');

-- 
-- Dumping data for table user
--
INSERT INTO user VALUES
(1, 'management', '1', 1),
(2, 'client', '1', 2);

-- 
-- Dumping data for table screen
--
INSERT INTO screen VALUES
(1, 'screen01', '123', 1920, 1080),
(2, 'screen02', '123', 1920, 1080);

-- 
-- Dumping data for table panel
--
-- Table digital_signage.panel does not contain any data (it is empty)

-- 
-- Dumping data for table frame
--
-- Table digital_signage.frame does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;